// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxWn0ma-SsI7OgFVvKQ7yRgDKdOQHX_PQ',
    appId: '1:751128874247:android:aa4e84962b6dcdaeef49a2',
    messagingSenderId: '751128874247',
    projectId: 'vitocars-4212c',
    storageBucket: 'vitocars-4212c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3xXie240GWzsElMNaKQZ6UOM7vCiHi6Y',
    appId: '1:751128874247:ios:da0417e44a8ce9fdef49a2',
    messagingSenderId: '751128874247',
    projectId: 'vitocars-4212c',
    storageBucket: 'vitocars-4212c.appspot.com',
    androidClientId: '751128874247-3ato5sac5vv5vlimt87j707aeh74uqm7.apps.googleusercontent.com',
    iosClientId: '751128874247-kvrg83chubbif3h7pc338qigmcjp71ng.apps.googleusercontent.com',
    iosBundleId: 'com.example.vitocars',
  );
}
